### ISSUE TITLE
https-agent-* is a bit unclear

### ISSUE THREAD

**Issue by NorseGaud** [veertuinc/anka-actions-up#9]
```
https-agent-cert:
  description: 'Certificate'
  required: false
https-agent-cert-passphrase:
  description: 'Certificate passphrase'
  required: false
https-agent-key:
  description: 'Private key'
  required: false
```

These param names are just a bit confusing. Can we change the names to `auth-cert`, `auth-cert-passphrase`, and `auth-cert-key`?

Also, ensure the description indicates it's for `Certificate Authentication`.
